---
title: '&nbsp;'
date: 'Last update: 05 November, 2021'
output:
  html_document:
    includes:
      before_body: /home/runner/work/systemPipeR/systemPipeR/docs/reference/.SPRproject/log_plot.html
    number_sections: false
    theme: flatly
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
package: systemPipeR
fontsize: 14pt
---

#  echo 

##  M1 

Time: Nov052021_0211s16


### Code: 
```{r, eval=FALSE} 
echo Hello World! > results/M1.txt
```


### Stdout: 
```{r, eval=FALSE}

```
##  M2 

Time: Nov052021_0211s16


### Code: 
```{r, eval=FALSE} 
echo Hello USA! > results/M2.txt
```


### Stdout: 
```{r, eval=FALSE}

```
##  M3 

Time: Nov052021_0211s16


### Code: 
```{r, eval=FALSE} 
echo Hello Bioconductor! > results/M3.txt
```


### Stdout: 
```{r, eval=FALSE}

```
#  R_read 

Time: Nov052021_0211s16


## Code: 
```{r, eval=FALSE} 
hello <- lapply(getColumn(sal, step = 1, "outfiles"), function(x) yaml::read_yaml(x))
```


## Stdout: 
```{r, eval=FALSE}
$M1
[1] "Hello World!"

$M2
[1] "Hello USA!"

$M3
[1] "Hello Bioconductor!"

``` 

