---
title: "Simple Workflow by systemPipeR" 
author: "Author: Daniela Cassol, Le Zhang, and Thomas Girke"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`" 
output:
  BiocStyle::html_document:
    toc_float: true
    code_folding: show
package: systemPipeR
vignette: |
  %\VignetteEncoding{UTF-8}
  %\VignetteIndexEntry{Workflow example}
  %\VignetteEngine{knitr::rmarkdown}
fontsize: 14pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Build the Workflow 

- Load `systemPipeR` library:

```{r load_library, eval=FALSE, spr='r', spr.req='mandatory', spr.ses='management'}
appendStep(sal) <- LineWise(code={
    library(systemPipeR)
    },
    step_name = 'load_library',
    dependency = NA,
    run_step = c('mandatory'),
    run_session = c('management'))
```



## Export dataset to file

- Add first step as `LineWise`

```{r export_iris, eval=FALSE, spr='r', spr.req='mandatory', spr.ses='management'}
appendStep(sal) <- LineWise(code={
    mapply(function(x, y) write.csv(x, y), split(iris, factor(iris$Species)), file.path("results", paste0(names(split(iris, factor(iris$Species))), ".csv")))
    },
    step_name = 'export_iris',
    dependency = NA,
    run_step = c('mandatory'),
    run_session = c('management'))
```



## Compress data

- Adding the second step, as `SYSargs2` 

```{r gzip, eval=FALSE, spr='sysargs', spr.dep='export_iris', spr.req='mandatory', spr.ses='management'}
appendStep(sal) <- SYSargsList(
    targets = "/home/runner/work/systemPipeR/systemPipeR/inst/extdata/cwl/gunzip/targets_gunzip.txt",
    dir_path="/home/runner/work/systemPipeR/systemPipeR/inst/extdata/cwl",
    wf_file="gunzip/workflow_gzip.cwl",
    input_file="gunzip/gzip.yml",
    inputvars = c( FileName="_FILE_PATH_", SampleName="_SampleName_" ),
    rm_targets_col = NULL,
    step_name = 'gzip',
    dependency = c('export_iris'),
    dir=TRUE,
    run_step = c('mandatory'),
    run_session = c('management')
)
```



## Decompress data

```{r gunzip, eval=FALSE, spr='sysargs', spr.dep='gzip', spr.req='mandatory', spr.ses='management'}
appendStep(sal) <- SYSargsList(
    targets = c("gzip"),
    dir_path="/home/runner/work/systemPipeR/systemPipeR/inst/extdata/cwl",
    wf_file="gunzip/workflow_gunzip.cwl",
    input_file="gunzip/gunzip.yml",
    inputvars = c( gzip_file="_FILE_PATH_", SampleName="_SampleName_" ),
    rm_targets_col = c(" FileName "),
    step_name = 'gunzip',
    dependency = c('gzip'),
    dir=TRUE,
    run_step = c('mandatory'),
    run_session = c('management')
)
```



## Import data to R and perform statistical analysis and visualization 

```{r stats, eval=FALSE, spr='r', spr.dep='gunzip', spr.req='optional', spr.ses='management'}
appendStep(sal) <- LineWise(code={
    df <- lapply(getColumn(sal, step = "gunzip", "outfiles"), function(x) read.delim(x, sep = ",")[-1])
    df <- do.call(rbind, df)
    stats <- data.frame(cbind(mean = apply(df[, 1:4], 2, mean), sd = apply(df[, 1:4], 2, sd)))
    stats$species <- rownames(stats)
    plot <- ggplot2::ggplot(stats, ggplot2::aes(x = species, y = mean, fill = species)) + ggplot2::geom_bar(stat = "identity", color = "black", position = ggplot2::position_dodge()) + ggplot2::geom_errorbar(ggplot2::aes(ymin = mean - sd, ymax = mean + sd), width = 0.2, position = ggplot2::position_dodge(0.9))
    },
    step_name = 'stats',
    dependency = c('gunzip'),
    run_step = c('optional'),
    run_session = c('management'))
```


# Step6 echo
```{r echo, eval=FALSE, spr='sysargs', spr.req='mandatory', spr.ses='management'}
appendStep(sal) <- SYSargsList(
    targets = "/home/runner/work/systemPipeR/systemPipeR/inst/extdata/cwl/example/targets_example.txt",
    dir_path="/home/runner/work/systemPipeR/systemPipeR/inst/extdata/cwl",
    wf_file="example/workflow_example.cwl",
    input_file="example/example.yml",
    inputvars = c( Message="_STRING_", SampleName="_SAMPLE_" ),
    rm_targets_col = NULL,
    step_name = 'echo',
    dependency = NA,
    dir=TRUE,
    run_step = c('mandatory'),
    run_session = c('management')
)
```


