---
title: "Publications" 
author: "Author: Daniela Cassol (danielac@ucr.edu)"
date: "Last update: `r format(Sys.time(), '%d %B, %Y')`" 
output:
  BiocStyle::html_document:
    toc_float: true
    code_folding: show
  BiocStyle::pdf_document: default
package: systemPipeR
type: docs
weight: 3
exclude_search: true
---

## Publications of this project 

### Journal publications

- Duan Y, Evans DS, Miller RA, Schork NJ, Cummings SR, Girke T. signatureSearch: environment for gene expression signature searching and functional interpretation. Nucleic Acids Res [Internet]. 2020 Dec 2;48(21):e124. Available from: http://dx.doi.org/10.1093/nar/gkaa878 PMCID: [PMC7708038{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7708038/)

- Lombard DB, Kohler WJ, Guo AH, Gendron C, Han M, Ding W, Lyu Y, Ching T-T, Wang F-Y, Chakraborty TS, Nikolovska-Coleska Z, Duan Y, Girke T, Hsu A-L, Pletcher SD, Miller RA. High-throughput small molecule screening reveals Nrf2-dependent and -independent pathways of cellular stress resistance. Sci Adv [Internet]. 2020 Oct;6(40). Available from: http://dx.doi.org/10.1126/sciadv.aaz7628 PMCID: [PMC7852388{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7852388/)

- Hamilton MJ, Young M, Jang K, Sauer S, Neang VE, King AT, Girke T, Martinez E. HOTAIRM1 lncRNA is downregulated in clear cell renal cell carcinoma and inhibits the hypoxia pathway. Cancer Lett [Internet]. 2020 Mar 1;472:50–58. Available from: http://dx.doi.org/10.1016/j.canlet.2019.12.022 PMCID: [PMC6992348{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6992348/)

- Pozuelos GL, Kagda MS, Schick S, Girke T, Volz DC, Talbot P. Experimental Acute Exposure to Thirdhand Smoke and Changes in the Human Nasal Epithelial Transcriptome: A Randomized Clinical Trial. JAMA Netw Open [Internet]. 2019 Jun 5;2(6):e196362. Available from: http://dx.doi.org/10.1001/jamanetworkopen.2019.6362 PMCID: [PMC6604097{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6604097/)

- Hamilton MJ, Girke T, Martinez E. Global isoform-specific transcript alterations and deregulated networks in clear cell renal cell carcinoma. Oncotarget [Internet]. 2018 May 4;9(34):23670–23680. Available from: http://dx.doi.org/10.18632/oncotarget.25330 PMCID: [PMC5955119{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5955119/)

- Teixeira MA, Sela N, Atamian HS, Bao E, Chaudhary R, MacWilliams J, He J, Mantelin S, Girke T, Kaloshian I. Sequence analysis of the potato aphid Macrosiphum euphorbiae transcriptome identified two new viruses. PLoS One [Internet]. Public Library of Science; 2018 Mar 29 [cited 2021 Apr 26];13(3):e0193239. Available from: https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0193239&type=printable PMCID: [PMC5875755{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5875755/)

- Zillikens MC, et al. Large meta-analysis of genome-wide association studies identifies five loci for lean body mass. Nat Commun [Internet]. Nature Publishing Group; 2017 Jul 19 [cited 2021 Apr 26];8(1):1–13. Available from: https://www.nature.com/articles/s41467-017-00031-7 PMCID: 29116125

- Zhang X, Aksoy E, Girke T, Raikhel AS, Karginov FV. Transcriptome-wide microRNA and target dynamics in the fat body during the gonadotrophic cycle of Aedes aegypti. Proc Natl Acad Sci U S A [Internet]. 2017 Mar 7;114(10):E1895–E1903. Available from: http://dx.doi.org/10.1073/pnas.1701474114 PMCID: [PMC5347622{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5347622/)

- H Backman TW, Girke T. systemPipeR: NGS workflow and report generation environment. BMC Bioinformatics [Internet]. 2016 Sep 20;17:388. Available from: http://dx.doi.org/10.1186/s12859-016-1241-0 PMCID: [PMC5029110{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5029110/)

## Publications related to this project

[[ PubMed ]](https://pubmed.ncbi.nlm.nih.gov/?sort=pubdate&size=50&linkname=pubmed_pubmed_citedin&from_uid=27650223) - [[ Google Scholar ]](https://scholar.google.com/scholar?oi=bibs&hl=en&cites=6906051125040672859)

- Chen Y, Liu M, Dong Z. Preferential Ribosome Loading on the Stress-Upregulated mRNA Pool Shapes the Selective Translation under Stress Conditions. Plants [Internet]. 2021 Feb 5;10(2). Available from: http://dx.doi.org/10.3390/plants10020304 PMCID: [PMC7915710{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7915710/)

- Lima TS, Mallya S, Jankeel A, Messaoudi I, Lodoen MB. Toxoplasma gondii Extends the Life Span of Infected Human Neutrophils by Inducing Cytosolic PCNA and Blocking Activation of Apoptotic Caspases. MBio [Internet]. 2021 Jan 26;12(1). Available from: http://dx.doi.org/10.1128/mBio.02031-20 PMCID: [PMC7858050{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7858050/)

- Furuyama W, Shifflett K, Pinski AN, Griffin AJ, Feldmann F, Okumura A, Gourdine T, Jankeel A, Lovaglio J, Hanley PW, Thomas T, Clancy CS, Messaoudi I, O’Donnell KL, Marzi A. Rapid protection from COVID-19 in nonhuman primates vaccinated intramuscularly but not intranasally with a single dose of a recombinant vaccine. bioRxiv [Internet]. 2021 Jan 19; Available from: http://dx.doi.org/10.1101/2021.01.19.426885 PMCID: [PMC7836117{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7836117/)

- Procida T, Friedrich T, Jack APM, Peritore M, Bönisch C, Eberl HC, Daus N, Kletenkov K, Nist A, Stiewe T, Borggrefe T, Mann M, Bartkuhn M, Hake SB. JAZF1, A Novel p400/TIP60/NuA4 Complex Member, Regulates H2A.Z Acetylation at Regulatory Regions. Int J Mol Sci [Internet]. 2021 Jan 12;22(2). Available from: http://dx.doi.org/10.3390/ijms22020678 PMCID: [PMC7826843{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7826843/)

- Chen L, Walker AR, Burne RA, Zeng L. Amino Sugars Reshape Interactions between Streptococcus mutans and Streptococcus gordonii. Appl Environ Microbiol [Internet]. 2020 Dec 17;87(1). Available from: http://dx.doi.org/10.1128/AEM.01459-20 PMCID: [PMC7755246{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7755246/)

- Duan Y, Evans DS, Miller RA, Schork NJ, Cummings SR, Girke T. signatureSearch: environment for gene expression signature searching and functional interpretation. Nucleic Acids Res [Internet]. 2020 Dec 2;48(21):e124. Available from: http://dx.doi.org/10.1093/nar/gkaa878 PMCID: [PMC7708038{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7708038/)

- Li K, Hope CM, Wang XA, Wang J-P. RiboDiPA: a novel tool for differential pattern analysis in Ribo-seq data. Nucleic Acids Res [Internet]. 2020 Dec 2;48(21):12016–12029. Available from: http://dx.doi.org/10.1093/nar/gkaa1049 PMCID: [PMC7708064{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7708064/)

- Berg JA, Hermans FWK, Beenders F, Lou L, Vriezen WH, Visser RGF, Bai Y, Schouten HJ. Analysis of QTL DM4.1 for Downy Mildew Resistance in Cucumber Reveals Multiple subQTL: A Novel RLK as Candidate Gene for the Most Important subQTL. Front Plant Sci [Internet]. 2020 Oct 22;11:569876. Available from: http://dx.doi.org/10.3389/fpls.2020.569876 PMCID: [PMC7649820{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7649820/)

- Kagda MS, Martínez-Soto D, Ah-Fong AMV, Judelson HS. Invertases in Phytophthora infestans Localize to Haustoria and Are Programmed for Infection-Specific Expression. MBio [Internet]. 2020 Oct 13;11(5). Available from: http://dx.doi.org/10.1128/mBio.01251-20 PMCID: [PMC7554665{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7554665/)

- Lou B, Boger M, Bennewitz K, Sticht C, Kopf S, Morgenstern J, Fleming T, Hell R, Yuan Z, Nawroth PP, Kroll J. Elevated 4-hydroxynonenal induces hyperglycaemia via Aldh3a1 loss in zebrafish and associates with diabetes progression in humans. Redox Biol [Internet]. 2020 Oct;37:101723. Available from: http://dx.doi.org/10.1016/j.redox.2020.101723 PMCID: [PMC7519378{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7519378/)

- Iwanami N, Lawir D-F, Sikora K, O Meara C, Takeshita K, Schorpp M, Boehm T. Transgenerational inheritance of impaired larval T cell development in zebrafish. Nat Commun [Internet]. 2020 Sep 9;11(1):4505. Available from: http://dx.doi.org/10.1038/s41467-020-18289-9 PMCID: [PMC7481223{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7481223/)

- Akbarzadeh A, Houde ALS, Sutherland BJG, Günther OP, Miller KM. Identification of Hypoxia-Specific Biomarkers in Salmonids Using RNA-Sequencing and Validation Using High-Throughput qPCR. G3 [Internet]. 2020 Sep 2;10(9):3321–3336. Available from: http://dx.doi.org/10.1534/g3.120.401487 PMCID: [PMC7466982{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7466982/)

- Li F, Xing X, Xiao Z, Xu G, Yang X. RiboMiner: a toolset for mining multi-dimensional features of the translatome with ribosome profiling data. BMC Bioinformatics [Internet]. 2020 Aug 1;21(1):340. Available from: http://dx.doi.org/10.1186/s12859-020-03670-8 PMCID: [PMC7430821{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7430821/)

- Fernández-Calero T, Davyt M, Perelmuter K, Chalar C, Bampi G, Persson H, Tosar JP, Hafstað V, Naya H, Rovira C, Bollati-Fogolín M, Ehrlich R, Flouriot G, Ignatova Z, Marín M. Fine-tuning the metabolic rewiring and adaptation of translational machinery during an epithelial-mesenchymal transition in breast cancer cells. Cancer Metab [Internet]. 2020 Jul 19;8:8. Available from: http://dx.doi.org/10.1186/s40170-020-00216-7 PMCID: [PMC7368990{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7368990/)

- Liu Q, Shvarts T, Sliz P, Gregory RI. RiboToolkit: an integrated platform for analysis and annotation of ribosome profiling data to decode mRNA translation at codon resolution. Nucleic Acids Res [Internet]. 2020 Jul 2;48(W1):W218–W229. Available from: http://dx.doi.org/10.1093/nar/gkaa395 PMCID: [PMC7319539{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7319539/)

- Alam R, Hummel M, Yeung E, Locke AM, Ignacio JCI, Baltazar MD, Jia Z, Ismail AM, Septiningsih EM, Bailey-Serres J. Flood resilience loci SUBMERGENCE 1 and ANAEROBIC GERMINATION 1 interact in seedlings established underwater. Plant Direct [Internet]. 2020 Jul;4(7):e00240. Available from: http://dx.doi.org/10.1002/pld3.240 PMCID: [PMC7403837{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7403837/)

- Ehrary A, Rosas M, Carpinelli S, Davalos O, Cowling C, Fernandez F, Escobar M. Glutaredoxin AtGRXS8 represses transcriptional and developmental responses to nitrate in Arabidopsis thaliana roots. Plant Direct [Internet]. 2020 Jun;4(6):e00227. Available from: http://dx.doi.org/10.1002/pld3.227 PMCID: [PMC7287413{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7287413/)

- Jankeel A, Menicucci AR, Woolsey C, Fenton KA, Mendoza N, Versteeg K, Cross RW, Geisbert TW, Messaoudi I. Early Transcriptional Changes within Liver, Adrenal Gland, and Lymphoid Tissues Significantly Contribute to Ebola Virus Pathogenesis in Cynomolgus Macaques. J Virol [Internet]. 2020 May 18;94(11). Available from: http://dx.doi.org/10.1128/JVI.00250-20 PMCID: [PMC7269430{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7269430/)

- Gómez-Martín C, Capel C, González AM, Lebrón R, Yuste-Lisbona FJ, Hackenberg M, Oliver JL, Santalla M, Lozano R. Transcriptional Dynamics and Candidate Genes Involved in Pod Maturation of Common Bean (Phaseolus vulgaris L.). Plants [Internet]. 2020 Apr 22;9(4). Available from: http://dx.doi.org/10.3390/plants9040545 PMCID: [PMC7238275{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7238275/)

- Lee SC, Ernst E, Berube B, Borges F, Parent J-S, Ledon P, Schorn A, Martienssen RA. Arabidopsis retrotransposon virus-like particles and their regulation by epigenetically activated small RNA. Genome Res [Internet]. 2020 Apr;30(4):576–588. Available from: http://dx.doi.org/10.1101/gr.259044.119 PMCID: [PMC7197481{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7197481/)

- Hamilton MJ, Young M, Jang K, Sauer S, Neang VE, King AT, Girke T, Martinez E. HOTAIRM1 lncRNA is downregulated in clear cell renal cell carcinoma and inhibits the hypoxia pathway. Cancer Lett [Internet]. 2020 Mar 1;472:50–58. Available from: http://dx.doi.org/10.1016/j.canlet.2019.12.022 PMCID: [PMC6992348{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6992348/)

- Bjorbækmo MFM, Evenstad A, Røsæg LL, Krabberød AK, Logares R. The planktonic protist interactome: where do we stand after a century of research? ISME J [Internet]. 2020 Feb;14(2):544–559. Available from: http://dx.doi.org/10.1038/s41396-019-0542-5 PMCID: [PMC6976576{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6976576/)

- Meng H, Feng J, Bai T, Jian Z, Chen Y, Wu G. Genome-wide analysis of short interspersed nuclear elements provides insight into gene and genome evolution in citrus. DNA Res [Internet]. 2020 Feb 1;27(1). Available from: http://dx.doi.org/10.1093/dnares/dsaa004 PMCID: [PMC7315354{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7315354/)

- Irigoyen ML, Garceau DC, Bohorquez-Chaux A, Lopez-Lavalle LAB, Perez-Fons L, Fraser PD, Walling LL. Genome-wide analyses of cassava Pathogenesis-related (PR) gene families reveal core transcriptome responses to whitefly infestation, salicylic acid and jasmonic acid. BMC Genomics [Internet]. 2020 Jan 29;21(1):93. Available from: http://dx.doi.org/10.1186/s12864-019-6443-1 PMCID: [PMC6990599{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6990599/)

- Franklin-Murray AL, Mallya S, Jankeel A, Sureshchandra S, Messaoudi I, Lodoen MB. Toxoplasma gondii Dysregulates Barrier Function and Mechanotransduction Signaling in Human Endothelial Cells. mSphere [Internet]. 2020 Jan 29;5(1). Available from: http://dx.doi.org/10.1128/mSphere.00550-19 PMCID: [PMC6992369{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6992369/)

- Berg JA, Belyeu JR, Morgan JT, Ouyang Y, Bott AJ, Quinlan AR, Gertz J, Rutter J. XPRESSyourself: Enhancing, standardizing, and automating ribosome profiling computational analyses yields improved insight into data. PLoS Comput Biol [Internet]. 2020 Jan;16(1):e1007625. Available from: http://dx.doi.org/10.1371/journal.pcbi.1007625 PMCID: [PMC7015430{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7015430/)

- Zhao C, Rispe C, Nabity PD. Secretory RING finger proteins function as effectors in a grapevine galling insect. BMC Genomics [Internet]. 2019 Dec 3;20(1):923. Available from: http://dx.doi.org/10.1186/s12864-019-6313-x PMCID: [PMC6892190{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6892190/)

- Dhahbi J, Nunez Lopez YO, Schneider A, Victoria B, Saccon T, Bharat K, McClatchey T, Atamna H, Scierski W, Golusinski P, Golusinski W, Masternak MM. Profiling of tRNA Halves and YRNA Fragments in Serum and Tissue From Oral Squamous Cell Carcinoma Patients Identify Key Role of 5’ tRNA-Val-CAC-2-1 Half. Front Oncol [Internet]. 2019 Sep 26;9:959. Available from: http://dx.doi.org/10.3389/fonc.2019.00959 PMCID: [PMC6775249{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6775249/)

- Woolsey C, Menicucci AR, Cross RW, Luthra P, Agans KN, Borisevich V, Geisbert JB, Mire CE, Fenton KA, Jankeel A, Anand S, Ebihara H, Geisbert TW, Messaoudi I, Basler CF. A VP35 Mutant Ebola Virus Lacks Virulence but Can Elicit Protective Immunity to Wild-Type Virus Challenge. Cell Rep [Internet]. 2019 Sep 17;28(12):3032–3046.e6. Available from: http://dx.doi.org/10.1016/j.celrep.2019.08.047 PMCID: [PMC6886687{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6886687/)

- Smestad JA, Maher LJ 3rd. Master regulator analysis of paragangliomas carrying SDHx, VHL, or MAML3 genetic alterations. BMC Cancer [Internet]. 2019 Jun 24;19(1):619. Available from: http://dx.doi.org/10.1186/s12885-019-5813-z PMCID: [PMC6591808{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6591808/)

- Perkins P, Mazzoni-Putman S, Stepanova A, Alonso J, Heber S. RiboStreamR: a web application for quality control, analysis, and visualization of Ribo-seq data. BMC Genomics [Internet]. 2019 Jun 6;20(Suppl 5):422. Available from: http://dx.doi.org/10.1186/s12864-019-5700-7 PMCID: [PMC6551240{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6551240/)

- Pozuelos GL, Kagda MS, Schick S, Girke T, Volz DC, Talbot P. Experimental Acute Exposure to Thirdhand Smoke and Changes in the Human Nasal Epithelial Transcriptome: A Randomized Clinical Trial. JAMA Netw Open [Internet]. 2019 Jun 5;2(6):e196362. Available from: http://dx.doi.org/10.1001/jamanetworkopen.2019.6362 PMCID: [PMC6604097{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6604097/)

- Barr T, Lewis SA, Sureshchandra S, Doratt B, Grant KA, Messaoudi I. Chronic ethanol consumption alters lamina propria leukocyte response to stimulation in a region-dependent manner. FASEB J [Internet]. 2019 Jun;33(6):7767–7777. Available from: http://dx.doi.org/10.1096/fj.201802780R PMCID: [PMC6529332{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6529332/)

- Menicucci AR, Jankeel A, Feldmann H, Marzi A, Messaoudi I. Antiviral Innate Responses Induced by VSV-EBOV Vaccination Contribute to Rapid Protection. MBio [Internet]. 2019 May 28;10(3). Available from: http://dx.doi.org/10.1128/mBio.00597-19 PMCID: [PMC6538780{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6538780/)

- Babarinde IA, Li Y, Hutchins AP. Computational Methods for Mapping, Assembly and Quantification for Coding and Non-coding Transcripts. Comput Struct Biotechnol J [Internet]. 2019 May 7;17:628–637. Available from: http://dx.doi.org/10.1016/j.csbj.2019.04.012 PMCID: [PMC6526290{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6526290/)

- Karginov FV. HuR controls apoptosis and activation response without effects on cytokine 3’ UTRs. RNA Biol [Internet]. 2019 May;16(5):686–695. Available from: http://dx.doi.org/10.1080/15476286.2019.1582954 PMCID: [PMC6546391{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6546391/)

- Blair EJ, Bonnot T, Hummel M, Hay E, Marzolino JM, Quijada IA, Nagel DH. Contribution of time of day and the circadian clock to the heat stress responsive transcriptome in Arabidopsis. Sci Rep [Internet]. 2019 Mar 18;9(1):4814. Available from: http://dx.doi.org/10.1038/s41598-019-41234-w PMCID: [PMC6423321{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6423321/)

- Joo T, Choi J-H, Lee J-H, Park SE, Jeon Y, Jung SH, Woo HG. SEQprocess: a modularized and customizable pipeline framework for NGS processing in R package. BMC Bioinformatics [Internet]. 2019 Feb 20;20(1):90. Available from: http://dx.doi.org/10.1186/s12859-019-2676-x PMCID: [PMC6383233{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6383233/)

- Nunez Lopez YO, Retnakaran R, Zinman B, Pratley RE, Seyhan AA. Predicting and understanding the response to short-term intensive insulin therapy in people with early type 2 diabetes. Mol Metab [Internet]. 2019 Feb;20:63–78. Available from: http://dx.doi.org/10.1016/j.molmet.2018.11.003 PMCID: [PMC6358589{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6358589/)

- Shultzaberger RK, Abrams RE, Sullivan CJ, Schmitt AD, Thompson TWJ, Dresios J. Agnostic detection of genomic alterations by holistic DNA structural interrogation. PLoS One [Internet]. 2018 Nov 29;13(11):e0208054. Available from: http://dx.doi.org/10.1371/journal.pone.0208054 PMCID: [PMC6264503{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6264503/)

- Gongol B, Sari I, Bryant T, Rosete G, Marin T. AMPK: An Epigenetic Landscape Modulator. Int J Mol Sci [Internet]. 2018 Oct 19;19(10). Available from: http://dx.doi.org/10.3390/ijms19103238 PMCID: [PMC6214086{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6214086/)

- Jacobsen MD, Beynon RJ, Gethings LA, Claydon AJ, Langridge JI, Vissers JPC, Brown AJP, Hammond DE. Specificity of the osmotic stress response in Candida albicans highlighted by quantitative proteomics. Sci Rep [Internet]. 2018 Sep 27;8(1):14492. Available from: http://dx.doi.org/10.1038/s41598-018-32792-6 PMCID: [PMC6160413{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6160413/)

- Mazzoni-Putman SM, Stepanova AN. A Plant Biologist’s Toolbox to Study Translation. Front Plant Sci [Internet]. 2018 Jul 2;9:873. Available from: http://dx.doi.org/10.3389/fpls.2018.00873 PMCID: [PMC6036148{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6036148/)

- Hamilton MJ, Girke T, Martinez E. Global isoform-specific transcript alterations and deregulated networks in clear cell renal cell carcinoma. Oncotarget [Internet]. 2018 May 4;9(34):23670–23680. Available from: http://dx.doi.org/10.18632/oncotarget.25330 PMCID: [PMC5955119{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5955119/)

- Eastman G, Smircich P, Sotelo-Silveira JR. Following Ribosome Footprints to Understand Translation at a Genome Wide Level. Comput Struct Biotechnol J [Internet]. 2018 May 1;16:167–176. Available from: http://dx.doi.org/10.1016/j.csbj.2018.04.001 PMCID: [PMC6066590{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6066590/)

- Smestad J, Hamidi O, Wang L, Holte MN, Khazal FA, Erber L, Chen Y, Maher LJ 3rd. Characterization and metabolic synthetic lethal testing in a new model of SDH-loss familial pheochromocytoma and paraganglioma. Oncotarget [Internet]. 2018 Jan 19;9(5):6109–6127. Available from: http://dx.doi.org/10.18632/oncotarget.23639 PMCID: [PMC5814199{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5814199/)

- Marzi A, Menicucci AR, Engelmann F, Callison J, Horne EJ, Feldmann F, Jankeel A, Feldmann H, Messaoudi I. Protection Against Marburg Virus Using a Recombinant VSV-Vaccine Depends on T and B Cell Activation. Front Immunol [Internet]. 2018;9:3071. Available from: http://dx.doi.org/10.3389/fimmu.2018.03071 PMCID: [PMC6350103{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc6350103/)

- Abrahamian M, Kagda M, Ah-Fong AMV, Judelson HS. Rethinking the evolution of eukaryotic metabolism: novel cellular partitioning of enzymes in stramenopiles links serine biosynthesis to glycolysis in mitochondria. BMC Evol Biol [Internet]. 2017 Dec 4;17(1):241. Available from: http://dx.doi.org/10.1186/s12862-017-1087-8 PMCID: [PMC5715807{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5715807/)

- Bazin J, Baerenfaller K, Gosai SJ, Gregory BD, Crespi M, Bailey-Serres J. Global analysis of ribosome-associated noncoding RNAs unveils new modes of translational regulation. Proc Natl Acad Sci U S A [Internet]. 2017 Nov 14;114(46):E10018–E10027. Available from: http://dx.doi.org/10.1073/pnas.1708433114 PMCID: [PMC5699049{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5699049/)

- Weisberg AJ, Kim G, Westwood JH, Jelesko JG. Sequencing and De Novo Assembly of the Toxicodendron radicans (Poison Ivy) Transcriptome. Genes [Internet]. 2017 Nov 10;8(11). Available from: http://dx.doi.org/10.3390/genes8110317 PMCID: [PMC5704230{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5704230/)

- Menicucci AR, Versteeg K, Woolsey C, Mire CE, Geisbert JB, Cross RW, Agans KN, Jankeel A, Geisbert TW, Messaoudi I. Transcriptome Analysis of Circulating Immune Cell Subsets Highlight the Role of Monocytes in Zaire Ebola Virus Makona Pathogenesis. Front Immunol [Internet]. 2017 Oct 26;8:1372. Available from: http://dx.doi.org/10.3389/fimmu.2017.01372 PMCID: [PMC5662559{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5662559/)

- Versteeg K, Menicucci AR, Woolsey C, Mire CE, Geisbert JB, Cross RW, Agans KN, Jeske D, Messaoudi I, Geisbert TW. Infection with the Makona variant results in a delayed and distinct host immune response compared to previous Ebola virus variants. Sci Rep [Internet]. 2017 Aug 29;7(1):9730. Available from: http://dx.doi.org/10.1038/s41598-017-09963-y PMCID: [PMC5574898{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5574898/)

- Arnold N, Meyer C, Engelmann F, Messaoudi I. Robust gene expression changes in the ganglia following subclinical reactivation in rhesus macaques infected with simian varicella virus. J Neurovirol [Internet]. 2017 Aug;23(4):520–538. Available from: http://dx.doi.org/10.1007/s13365-017-0522-3 PMCID: [PMC5607069{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5607069/)

- Arnold N, Messaoudi I. Simian varicella virus causes robust transcriptional changes in T cells that support viral replication. Virus Res [Internet]. 2017 Jun 15;238:226–235. Available from: http://dx.doi.org/10.1016/j.virusres.2017.07.004 PMCID: [PMC7114558{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc7114558/)

- Menicucci AR, Sureshchandra S, Marzi A, Feldmann H, Messaoudi I. Transcriptomic analysis reveals a previously unknown role for CD8+ T-cells in rVSV-EBOV mediated protection. Sci Rep [Internet]. 2017 Apr 20;7(1):919. Available from: http://dx.doi.org/10.1038/s41598-017-01032-8 PMCID: [PMC5430516{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc5430516/)

- Barr T, Girke T, Sureshchandra S, Nguyen C, Grant K, Messaoudi I. Alcohol Consumption Modulates Host Defense in Rhesus Macaques by Altering Gene Expression in Circulating Leukocytes. J Immunol [Internet]. 2016 Jan 1;196(1):182–195. Available from: http://dx.doi.org/10.4049/jimmunol.1501527 PMCID: [PMC4685011{blk}](http://www.ncbi.nlm.nih.gov/pmc/articles/pmc4685011/)
