on:
  push:
    branches:
      - main
  schedule:
  - cron: "0 2 * * *"

name: update_pkg_reference_manuals

jobs:
  update_ref:
    name: update_pkg_reference_manuals
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Update reference
        run: |
          bash .github/bash/update_reference.sh https://github.com/lz100/spsUtil.git static/sps/funcs/spsutil
          bash .github/bash/update_reference.sh https://github.com/lz100/systemPipeShiny.git static/sps/funcs/sps
      - name: Update github
        run: |
          if [ -n "$(git status --porcelain)" ]; then
              echo "there are changes";
              git config --local user.name "Github Action Bot"
              git config --local user.email "gh-action-bot@protonmail.com"
              git add -A
              git commit -m "Bot update reference pg_build" -a
              echo "skip_build=false" >> $GITHUB_ENV
          else
              echo "no changes";
              echo "skip_build=true" >> $GITHUB_ENV
              exit 78
          fi
      - name: Push changes
        if: env.skip_build != 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install node pkgs
        run: |
          npm install -g postcss-cli
          npm install autoprefixer
          npm audit fix
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: blogdown-1-dep
          restore-keys: blogdown-1-dep
      - name: Install system dependencies
        run: bash .github/bash/install_system.sh
      - name: Install R dependencies
        run: Rscript R/solve_deps.R
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo(extended = TRUE)'
      - name: Run hugo_build()
        run: |
          Rscript -e 'blogdown::build_site(build_rmd = "md5sum")'
          Rscript -e 'writeLines(as.character(Sys.time()), "blogdown/timestamp.txt")'
      - name: Update github
        run: |
          git config --local user.name "dcassol"
          git config --local user.email "danicassol@gmail.com"
          git add -A
          git commit -m "Bot update public and md5sum table" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: systempipe.org

