on:
  push:
    branches:
      - main
  schedule:
  - cron: "0 2 * * *"

name: update_pkg_reference_manuals

jobs:
  update_ref:
    name: update_pkg_reference_manuals
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update reference
        run: |
          bash .github/bash/update_reference.sh https://github.com/lz100/spsUtil.git static/sps/funcs/spsutil
          bash .github/bash/update_reference.sh https://github.com/lz100/systemPipeShiny.git static/sps/funcs/sps
      - name: Update github
        run: |
          if [ -n "$(git status --porcelain)" ]; then
              echo "there are changes";
              git config --local user.name "Github Action Bot"
              git config --local user.email "gh-action-bot@protonmail.com"
              git add -A
              git commit -m "Bot update reference pg_build" -a
              echo "skip_build=false" >> $GITHUB_ENV
          else
              echo "no changes";
              echo "skip_build=true" >> $GITHUB_ENV
          fi
      - name: Push changes
        if: env.skip_build != 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

